url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

title: "Ally Radomski"

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 12
paginate_path: "/sketches/:num/"

future: true

collections:
  journal:
    output: true
  studio:
    output: true
  work:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"
      title: "Missing title"
      description: "Missing description"
      cover: "/assets/missing.png"
      permalink: /sketch/:title
  -
    scope:
      path: ""
      type: "work"
    values:
      layout: "post"
      title: "Missing title"
      description: "Missing description"
      cover: "/assets/missing.png"
      permalink: /work/:title
  -
    scope:
      path: ""
      type: "journal"
    values:
      layout: "post"
      permalink: /journal/:title
      sitemap: false
  -
    scope:
      path: ""
      type: "studio"
    values:
      layout: "studiopost"
      title: "Missing title"
      description: "Missing description"
      cover: "/assets/missing.png"
      permalink: /studio/:title

