url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

title: "Ally Radomski"

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 6
paginate_path: "/work/:num/"

permalink: pretty

collections:
  journal:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      title: "Missing title"
      description: "Missing description"
      cover: "/assets/missing.png"
  -
    scope:
      path: ""
      type: "journal"
    values:
      layout: "post"
      sitemap: false

